common/models/Cliente.php
<?php


Yii::import('common.models._base.BaseCliente');

class Cliente extends BaseCliente
{
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
        public function rules() {
                return array_merge(parent::rules(), array(
                    array('email','email'),
                ));
            
            }
            
        
        public function misClientes($id) {
		$criteria = new CDbCriteria;
		$criteria->compare('user_id', $id);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination'=>false,
		));
	}
        
        public function validarDueno($id){
            
            $user = Yii::app()->user->getId();
            $tipo_admin = User::model()->findByPk($user);
            if($id == $user OR $tipo_admin->tipo == 'Admin')
                return true;
            else
                return false;
                      
            
        }
}

frontend/controllers/ClienteController.php
<?php

class ClienteController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionListar() {
		$model = $this->loadModel(Yii::app()->user->id, 'User');
                $model_clientes= new Cliente;
                $model_clientes=$model_clientes->misClientes($model->id);
		$this->render('listar', array(
			'dataProvider' => $model_clientes,
		));
	}        
        
	public function actionVer($id) {
            
            $model = $this->loadModel($id, 'Cliente');
            if($model->validarDueno($model->user_id)){
                $model_ots= new Ot;
                $model_ots=$model_ots->misOts($id);
                    $this->render('ver', array(
                            'model' => $model,
                            'model_ots' => $model_ots,
                    ));
            }
            else
               throw new CHttpException(400, Yii::t('app', 'You are not authorized to perform this action.'));
        
	}

	public function actionCrear() {
		$model = new Cliente;
                $model->user_id = Yii::app()->user->id;

		$this->performAjaxValidation($model, 'cliente-form');

		if (isset($_POST['Cliente'])) {
			$model->setAttributes($_POST['Cliente']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('misClientes'));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}
        public function actionMisClientes() {

            $model = $this->loadModel(Yii::app()->user->id, 'User');
            $model_clientes= new Cliente;
            $model_clientes=$model_clientes->misClientes($model->id);
		$this->render('misClientes', array(
			'model' => $model,
                        'model_clientes' => $model_clientes,
                        
                       

		));
	}

	public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Cliente');

		$this->performAjaxValidation($model, 'cliente-form');

		if (isset($_POST['Cliente'])) {
			$model->setAttributes($_POST['Cliente']);

			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionBorrar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Cliente')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('administrar'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
             
        
        public function actionGenerarExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Cliente_model_search']))
               {
                $model = $session['Cliente_model_search'];
                $model = Cliente::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Cliente::model()->findAll();
             $this->toExcel($model, array('id', 'user', 'nombre', 'telefono', 'celular', 'email'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGenerarPdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Cliente_model_search']))
               {
                $model = $session['Cliente_model_search'];
                $model = Cliente::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Cliente::model()->findAll();
             $this->toExcel($model, array('id', 'user', 'nombre', 'telefono', 'celular', 'email'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}

}

frontend/controllers/OtController.php
<?php

class OtController extends GxController {

        public function filters() {
                return array('rights');
        }
	public function actionListar() {
		$dataProvider = new CActiveDataProvider('Ot');
		$this->render('listar', array(
			'dataProvider' => $dataProvider,
		));
	}    
        
	public function actionVer($id) {
            
            $model = $this->loadModel($id, 'Ot');
            if($model->validarDueno($model->cliente->user_id)){
		$this->render('ver', array(
			'model' => $model,
		));
            }            
            else
               throw new CHttpException(400, Yii::t('app', 'You are not authorized to perform this action.'));
        
        }
        
        public function actionCrearCliente($id) {
                
		$model = new Ot;                
                $model_cliente = $this->loadModel($id, 'Cliente');
                
                $model->cliente_id = $model_cliente->nombre;
                if(!$model->validarDueno($model_cliente->user_id))
                   throw new CHttpException(400, Yii::t('app', 'You are not authorized to perform this action.'));
                
                
                $model->fechaRegistro = date("Y/m/d H:i:s");

		$this->performAjaxValidation($model, 'ot-form');

		if (isset($_POST['Ot'])) {
			$model->setAttributes($_POST['Ot']);
                        $model->cliente_id = $id;
			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('cliente/ver', 'id' => $model->cliente_id));
			}
		}
                
		$this->render('crearCliente', array( 'model' => $model, 'model_cliente' => $model_cliente));
	}

	public function actionCrear() {
		$model = new Ot;
                $model->fechaRegistro = date("Y/m/d H:i:s");
		$this->performAjaxValidation($model, 'ot-form');

		if (isset($_POST['Ot'])) {
			$model->setAttributes($_POST['Ot']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}
                $busqueda_id = Yii::app()->user->getId();
                $model_clientes=Cliente::model()->findAll('user_id=:userid',array(':userid'=>$busqueda_id));
		$this->render('crear', array( 'model' => $model,'model_clientes'=>$model_clientes));
	}
        
        public function actionMisOts(){
            
            $model = new Ot;
            
            $filtersForm=new FiltersForm;
            if (isset($_GET['FiltersForm']))
                $filtersForm->filters=$_GET['FiltersForm'];

            // Get rawData and create dataProvider
            $model_ots=Ot::model()->with(array('cliente'=>array(
                'condition'=>'t.cliente_id=cliente.id AND cliente.user_id = :user_id',
                'params'=>array(':user_id'=>Yii::app()->user->getId()),
            )))->findAll();
            
            
            
            $dataProvider=new CArrayDataProvider($model_ots);
            $filteredData=$filtersForm->filter($dataProvider);
            
            $busqueda_id = Yii::app()->user->getId();
                $model_clientes=Cliente::model()->findAll('user_id=:userid',array(':userid'=>$busqueda_id));
		
            // Render
            $this->render('misOts', array(
                'filtersForm' => $filtersForm,
                'model' => $dataProvider,
                'model_ot' => $model,
                'model_clientes' => $model_clientes,
            ));         
            
            //$this->render('misOts',array('model_ots'=>$model_ots));
            
            
        }

	public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Ot');
                
                if($model->validarDueno($model->cliente->user_id)){
                    $this->performAjaxValidation($model, 'ot-form');

		if (isset($_POST['Ot'])) {
			$model->setAttributes($_POST['Ot']);

			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}
                
                $busqueda_id = Yii::app()->user->getId();
                $model_clientes=Cliente::model()->findAll('user_id=:userid',array(':userid'=>$busqueda_id));
		$this->render('actualizar', array(
				'model' => $model,
                                'model_clientes' => $model_clientes,
				));
	}
               else
                    throw new CHttpException(400, Yii::t('app', 'You are not authorized to perform this action.'));
        
        }
        
        public function actionActualizarCliente($id) {
		$model = $this->loadModel($id, 'Ot');

		$this->performAjaxValidation($model, 'ot-form');

		if (isset($_POST['Ot'])) {
			$model->setAttributes($_POST['Ot']);

			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizarCliente', array(
				'model' => $model,
				));
	}

	public function actionBorrar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Ot')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('administrar'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}
        
        public function actionFinalizarOt($id){
            
            $model = $this->loadModel($id, 'Ot');
            
            $user_id = $model->cliente->user_id;
            if(!$model->validarDueno($user_id))
                   throw new CHttpException(400, Yii::t('app', 'You are not authorized to perform this action.'));
                            
            $model->fechaTermino = date("Y/m/d H:i:s");
            $model->estadoOt = "FINALIZADO";
            $model->save(FALSE);
            $this->redirect(array('ver', 'id' => $id));
        }
        
        public function actionEntregarOt($id){
            
            $model = $this->loadModel($id, 'Ot');
            
            $user_id = $model->cliente->user_id;
            if(!$model->validarDueno($user_id))
                   throw new CHttpException(400, Yii::t('app', 'You are not authorized to perform this action.'));
                
            $model->fechaEntrega = date("Y/m/d H:i:s");
            $model->estadoOt = "ENTREGADO";
            $model->save(FALSE);
            $this->redirect(array('ver', 'id' => $id));
        }
        
        public function actionPagarOt($id){
            
            $model = $this->loadModel($id, 'Ot');
            
            $user_id = $model->cliente->user_id;
            if(!$model->validarDueno($user_id))
                   throw new CHttpException(400, Yii::t('app', 'You are not authorized to perform this action.'));
                
            
            $model->estadoCuenta = "PAGADO";
            $model->save(FALSE);
            $this->redirect(array('ver', 'id' => $id));
        }
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
             
        
        public function actionGenerarExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Ot_model_search']))
               {
                $model = $session['Ot_model_search'];
                $model = Ot::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Ot::model()->findAll();
             $this->toExcel($model, array('id', 'cliente', 'fechaRegistro', 'caracteristicas', 'problema', 'solucion', 'precio', 'observaciones', 'estadoOt', 'fechaTermino', 'fechaEntrega', 'estadoCuenta'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGenerarPdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Ot_model_search']))
               {
                $model = $session['Ot_model_search'];
                $model = Ot::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Ot::model()->findAll();
             $this->toExcel($model, array('id', 'cliente', 'fechaRegistro', 'caracteristicas', 'problema', 'solucion', 'precio', 'observaciones', 'estadoOt', 'fechaTermino', 'fechaEntrega', 'estadoCuenta'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}

}

frontend/views/cliente/_busqueda.php
<div class="wide form">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'search-cliente-form',
	'action'=>Yii::app()->createUrl($this->route),
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
	'method'=>'get',
        'htmlOptions'=>array('class'=>'well'),
)); ?>

	<?php echo $form->textFieldControlGroup($model,'id', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->dropDownListControlGroup($model,'user_id', GxHtml::listDataEx(User::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'All') ));?>

	<?php echo $form->textFieldControlGroup($model,'nombre', array('span'=>3, 'maxlength'=>100)); ?>

	<?php echo $form->textFieldControlGroup($model,'telefono', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->textFieldControlGroup($model,'celular', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->textFieldControlGroup($model,'email', array('span'=>3, 'maxlength'=>45)); ?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton(Yii::t('app', 'Search'),  array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'icon'=>'white search'));?>
        <?php echo TbHtml::resetButton(Yii::t('app', 'Reset'), array('icon'=>'icon-remove-sign')); ?>
        </div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>


frontend/views/cliente/_formulario.php

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'cliente-form',
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
        'enableAjaxValidation' => true,
));
?>

	<p class="help-block">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		
		<?php echo $form->textFieldControlGroup($model,'nombre', array('span'=>3, 'maxlength'=>100)); ?>
		<?php echo $form->textFieldControlGroup($model,'telefono', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'celular', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'email', array('span'=>3, 'maxlength'=>45)); ?>

<?php echo TbHtml::formActions(array(
    TbHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'id'=>'buttonStateful', 'data-loading-text'=>  Yii::t('app', 'Loading...'))),
    TbHtml::resetButton(Yii::t('app', 'Reset')),
));
?>
<?php $this->endWidget(); ?>        
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonStateful.js', CClientScript::POS_END); ?>

frontend/views/cliente/_vista.php
<a class="buttonwell" href="<?php echo Yii::app()->controller->createUrl('ver', array('id' => $data->id));?>">
<div class="view well">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
        <?php echo GxHtml::encode($data->id); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('user_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->user)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('nombre')); ?>:
        <?php echo GxHtml::encode($data->nombre); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('telefono')); ?>:
        <?php echo GxHtml::encode($data->telefono); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('celular')); ?>:
        <?php echo GxHtml::encode($data->celular); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('email')); ?>:
        <?php echo GxHtml::encode($data->email); ?>
	<br />

</div>
</a>

frontend/views/cliente/actualizar.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('listar'),
	GxHtml::valueEx($model) => array('ver', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(       
        array('label'=>Yii::t('app', 'Operations')),
        array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
        array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
        array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('ver', 'id' => GxActiveRecord::extractPkValue($model, true)), 'icon'=>'eye-open'),
        array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), null); ?>

<?php
$this->renderPartial('_formulario', array(
		'model' => $model));
?>

frontend/views/cliente/administrar.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('listar'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Export')),
        array('label'=>Yii::t('app', 'Export to Excel'), 'url'=>Yii::app()->controller->createUrl('GenerarExcel'), 'linkOptions'=>array('target'=>'_blank'), 'icon'=>'download-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<div class="title-menu">
        <?php echo TbHtml::pageHeader(Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)), null); ?>
</div>

<p>
<?php echo Yii::t('app', 'Text Option Search'); ?></p>

<div class="buttons-admin">
<?php 
       echo CHtml::link(Yii::t('app', 'Advanced Search'),'#',array('class'=>'search-button btn'));
?>
</div>
<div class="search-form">
<?php $this->renderPartial('_busqueda', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id' => 'cliente-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
        'type'=>'striped bordered condensed',
        'template'=>"{summary}{items}{pager}",
        //'htmlOptions' => array(
        //                        'style' => 'overflow-y:auto;'
        //                                   .'table-layout:fixed;'
        //                                   .'white-space:nowrap;'
        //                                   ),       
	'columns' => array(
		'id',
		array(
				'name'=>'user_id',
				'value'=>'GxHtml::valueEx($data->user)',
				'filter'=>GxHtml::listDataEx(User::model()->findAllAttributes(null, true)),
				),
		'nombre',
		'telefono',
		'celular',
		'email',
        array(
                'class'=>'bootstrap.widgets.TbButtonColumn',
                'viewButtonUrl'=>'Yii::app()->createUrl(Yii::app()->controller->createUrl("ver"), array("id"=>$data->id))',
                'updateButtonUrl'=>'Yii::app()->createUrl(Yii::app()->controller->createUrl("actualizar"), array("id"=>$data->id))',
                'deleteButtonUrl'=>'Yii::app()->createUrl(Yii::app()->controller->createUrl("borrar"), array("id"=>$data->id))',
          ),                
	),
)); ?>

<?php
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').slideToggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('cliente-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

frontend/views/cliente/crear.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('listar'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'Mis') . ' ' . $model->label(2), 'url' => array('cliente/misClientes'),  'icon'=>'briefcase white'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left white'),
    array('label'=>Yii::t('app', 'Up'), 'url'=>'javascript:GoUp()', 'icon'=>'arrow-up white', 'id'=>'button-up'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()), null); ?>
<?php
$this->renderPartial('_formulario', array(
		'model' => $model,
		'buttons' => 'create'));
?>

frontend/views/cliente/listar.php
<?php

$this->breadcrumbs = array(
	Cliente::label(2),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'Create') . ' ' . Cliente::label(), 'url' => array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . Cliente::label(2), 'url' => array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
        array('label'=>Yii::t('app', 'Up'), 'url'=>'javascript:GoUp()', 'icon'=>'arrow-up', 'id'=>'button-up'),
);
?>
<?php echo TbHtml::pageHeader(GxHtml::encode(Cliente::label(2)), null); ?>

<?php $this->widget('bootstrap.widgets.TbListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_vista',
)); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl . '/js/scroll.js'); ?>

frontend/views/cliente/misClientes.php
<?php
$this->breadcrumbs = array(
	$model->label(2) => array('listar'),
	Yii::t('app', 'My clients'),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'Create') . ' Cliente', 'url'=>array('crear'), 'icon'=>'file white'),
        array('label'=>Yii::t('app', 'Export')),
        array('label'=>Yii::t('app', 'Export to Excel'), 'url'=>Yii::app()->controller->createUrl('GenerarExcel'), 'linkOptions'=>array('target'=>'_blank'), 'icon'=>'download-alt white'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left white'),
    array('label'=>Yii::t('app', 'Up'), 'url'=>'javascript:GoUp()', 'icon'=>'arrow-up white', 'id'=>'button-up'),
);
?>
<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . '  Clientes ' . GxHtml::encode(GxHtml::valueEx($model)), null); ?>
<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
            'username',
            'email',
	),
)); ?>

<p></br>
<?php
$this->widget('bootstrap.widgets.TbGridView', array(
    'type'=>'striped bordered',
    'dataProvider' => $model_clientes,
    'filter'=>new cliente,
    'enableSorting'=>false,
    'template'=> '{summary}{pager}{items}{pager}',
    'columns' => array(
                'nombre',
                'telefono',
                'celular',
                'email',
                
                array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
                        'htmlOptions'=>array('style'=>'width: 50px'),
			'template'=>'{view} {update}',
			'buttons'=>array(
				'view' => array(
					'label'=>'Ver Cliente',
					'url'=>'Yii::app()->createUrl("cliente/ver", array("id"=>$data->id))',
				),
				'update' => array(
					'label'=>'Actualizar Cliente',
					'url'=>'Yii::app()->createUrl("cliente/actualizar", array("id"=>$data->id))',
				),
			),
				
                ),
    ),
));?>

frontend/views/cliente/ver.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('listar'),
	GxHtml::valueEx($model),
);

$this->menu=array(
        array('label'=>Yii::t('app', 'Operations'),),
        array('label'=>Yii::t('app', 'Create') . ' OT', 'url'=>Yii::app()->createUrl('ot/crearCliente',array('id'=>$model->id)), 'icon'=>'file white'),
        array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('actualizar', 'id' => $model->id), 'icon'=>'pencil white'),
        array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('borrar', 'id' => $model->id), 'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?')), 'icon'=>'trash white'),

        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left white'),
    array('label'=>Yii::t('app', 'Up'), 'url'=>'javascript:GoUp()', 'icon'=>'arrow-up white', 'id'=>'button-up'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), null); ?>


<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
'telefono',
'celular',
'email',
	),
)); ?>

<?php
$this->widget('bootstrap.widgets.TbGridView', array(
    'type'=>'striped bordered',
    'dataProvider' => $model_ots,
    'enableSorting'=>false,
    'template'=> '{summary}{pager}{items}{pager}',
    'columns' => array(
                'fechaRegistro',
                'caracteristicas',
        	'problema',
                'solucion',
                'precio',
                'estadoOt',
                /*'fechaTermino',
                'fechaEntrega',*/
                'estadoCuenta',
                array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
                        'htmlOptions'=>array('style'=>'width: 50px'),
			'template'=>'{view} {update}',
			'buttons'=>array(
				'view' => array(
					'label'=>'Ver Ot',
					'url'=>'Yii::app()->createUrl("ot/ver", array("id"=>$data->id))',
				),
				'update' => array(
					'label'=>'Actualizar Ot',
					'url'=>'Yii::app()->createUrl("ot/actualizar", array("id"=>$data->id))',
				),
			),
				
                ),
    ),
));?>