backend/controllers/CalificacionController.php
<?php

class CalificacionController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionIndex() {
                $this->redirect(array('listar'));
	}

	public function actionListar() {
		$dataProvider = new CActiveDataProvider('Calificacion');
		$this->render('listar', array(
			'dataProvider' => $dataProvider,
		));
	}        
        
	public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'Calificacion'),
		));
	}

	public function actionCrear() {
		$model = new Calificacion;

		$this->performAjaxValidation($model, 'calificacion-form');

		if (isset($_POST['Calificacion'])) {
			$model->setAttributes($_POST['Calificacion']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Calificacion');

		$this->performAjaxValidation($model, 'calificacion-form');

		if (isset($_POST['Calificacion'])) {
			$model->setAttributes($_POST['Calificacion']);

			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionBorrar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Calificacion')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('administrar'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionAdministrar() {
                $session = new CHttpSession;
                $session->open();
		$model = new Calificacion('search');
		$model->unsetAttributes();

		if (isset($_GET['Calificacion'])){
			$model->setAttributes($_GET['Calificacion']);
                }

                $session['Calificacion_model_search'] = $model;
                
		$this->render('administrar', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
             
        
        public function actionGenerarExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Calificacion_model_search']))
               {
                $model = $session['Calificacion_model_search'];
                $model = Calificacion::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Calificacion::model()->findAll();
             $this->toExcel($model, array('id', 'alumno', 'evaluacion', 'nota'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGenerarPdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Calificacion_model_search']))
               {
                $model = $session['Calificacion_model_search'];
                $model = Calificacion::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Calificacion::model()->findAll();
             $this->toExcel($model, array('id', 'alumno', 'evaluacion', 'nota'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}

//-------------------------------------------------------------------------------------------------------------        
        
	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Calificacion'),
		));
	}

	public function actionCreate() {
		$model = new Calificacion;

		$this->performAjaxValidation($model, 'calificacion-form');

		if (isset($_POST['Calificacion'])) {
			$model->setAttributes($_POST['Calificacion']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Calificacion');

		$this->performAjaxValidation($model, 'calificacion-form');

		if (isset($_POST['Calificacion'])) {
			$model->setAttributes($_POST['Calificacion']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Calificacion')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

        //Index
	public function actionList() {
		$dataProvider = new CActiveDataProvider('Calificacion');
                //$this->render('index', array(
		$this->render('list', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Calificacion('search');
		$model->unsetAttributes();

		if (isset($_GET['Calificacion'])){
			$model->setAttributes($_GET['Calificacion']);
                }

                $session['Calificacion_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
}

backend/controllers/CursoController.php
<?php

class CursoController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionIndex() {
                $this->redirect(array('listar'));
	}

	public function actionListar() {
		$dataProvider = new CActiveDataProvider('Curso');
		$this->render('listar', array(
			'dataProvider' => $dataProvider,
		));
	}        
        
	public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'Curso'),
		));
	}

	public function actionCrear() {
		$model = new Curso;

		$this->performAjaxValidation($model, 'curso-form');

		if (isset($_POST['Curso'])) {
			$model->setAttributes($_POST['Curso']);
			$relatedData = array(
				'alumnos' => $_POST['Curso']['alumnos'] === '' ? null : $_POST['Curso']['alumnos'],
				);

			if ($model->saveWithRelated($relatedData)) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Curso');

		$this->performAjaxValidation($model, 'curso-form');

		if (isset($_POST['Curso'])) {
			$model->setAttributes($_POST['Curso']);
			$relatedData = array(
				'alumnos' => $_POST['Curso']['alumnos'] === '' ? null : $_POST['Curso']['alumnos'],
				);

			if ($model->saveWithRelated($relatedData)) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionBorrar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Curso')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('administrar'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionAdministrar() {
                $session = new CHttpSession;
                $session->open();
		$model = new Curso('search');
		$model->unsetAttributes();

		if (isset($_GET['Curso'])){
			$model->setAttributes($_GET['Curso']);
                }

                $session['Curso_model_search'] = $model;
                
		$this->render('administrar', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
             
        
        public function actionGenerarExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Curso_model_search']))
               {
                $model = $session['Curso_model_search'];
                $model = Curso::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Curso::model()->findAll();
             $this->toExcel($model, array('id', 'asignatura', 'profesor', 'semestre', 'anio'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGenerarPdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Curso_model_search']))
               {
                $model = $session['Curso_model_search'];
                $model = Curso::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Curso::model()->findAll();
             $this->toExcel($model, array('id', 'asignatura', 'profesor', 'semestre', 'anio'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}

//-------------------------------------------------------------------------------------------------------------        
        
	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Curso'),
		));
	}

	public function actionCreate() {
		$model = new Curso;

		$this->performAjaxValidation($model, 'curso-form');

		if (isset($_POST['Curso'])) {
			$model->setAttributes($_POST['Curso']);
			$relatedData = array(
				'alumnos' => $_POST['Curso']['alumnos'] === '' ? null : $_POST['Curso']['alumnos'],
				);

			if ($model->saveWithRelated($relatedData)) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Curso');

		$this->performAjaxValidation($model, 'curso-form');

		if (isset($_POST['Curso'])) {
			$model->setAttributes($_POST['Curso']);
			$relatedData = array(
				'alumnos' => $_POST['Curso']['alumnos'] === '' ? null : $_POST['Curso']['alumnos'],
				);

			if ($model->saveWithRelated($relatedData)) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Curso')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

        //Index
	public function actionList() {
		$dataProvider = new CActiveDataProvider('Curso');
                //$this->render('index', array(
		$this->render('list', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Curso('search');
		$model->unsetAttributes();

		if (isset($_GET['Curso'])){
			$model->setAttributes($_GET['Curso']);
                }

                $session['Curso_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
}

backend/controllers/UserController.php
<?php

class UserController extends GxController {


	public function filters() {
                return array('rights');
        }
        
	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'User'),
		));
	}

	public function actionCreate() {
		$model = new User;

		$this->performAjaxValidation($model, 'user-form');

		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);
                        $model->password = $model->hashPassword($model->password);
			if ($model->save()) {
                                Rights::assign($model->rol, $model->id);
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'User');

		$this->performAjaxValidation($model, 'user-form');

		if (isset($_POST['User'])) {
                        $password = $model->password;
			$model->setAttributes($_POST['User']);
			if($password !== $model->password){
				$model->password=$model->hashPassword($model->password);
			}
			if ($model->save()) {
                                foreach(Rights::getAssignedRoles($model->id) as $rol){
                                    Rights::revoke($rol->name, $model->id);
                                }
                                Rights::assign($model->rol, $model->id);
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'User')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('User');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new User('search');
		$model->unsetAttributes();

		if (isset($_GET['User'])){
			$model->setAttributes($_GET['User']);
                }

                $session['User_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['User_model_search']))
               {
                $model = $session['User_model_search'];
                $model = User::model()->findAll($model->search()->criteria);
               }
               else
                 $model = User::model()->findAll();
             
             $this->toExcel($model, array('id', 'username', 'password', 'email'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['User_model_search']))
               {
                $model = $session['User_model_search'];
                $model = User::model()->findAll($model->search()->criteria);
               }
               else
                 $model = User::model()->findAll();
             
             $this->toExcel($model, array('id', 'username', 'password', 'email'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
        
	public function actionChangePassword($id) {
            $model = $this->loadModel($id, 'User');
            if($model->id === Yii::app()->user->id){		
                $model->setScenario('changePassword');                
                $this->performAjaxValidation($model, 'user-change-password');

                if (isset($_POST['User'])) {
                        $model->setAttributes($_POST['User']);
                        if($model->hashPassword($model->password_anterior) === $model->password){
                            if($model->password_nuevo === $model->password_nuevo_repetir){
                                $model->password=$model->hashPassword($model->password_nuevo);
                                if ($model->save()) {
                                    $model->unsetAttributes(array('password_anterior', 'password_nuevo', 'password_nuevo_repetir'));
                                    Yii::app()->user->setFlash('success', '<strong>La contraseña ha sido cambiada exitosamente</strong>');                                    
                                }
                            }else{
                            $model->addError('password_nuevo', 'La nueva contraseña no coinciden.');  
                            $model->addError('password_nuevo_repetir', 'La nueva contraseña no coinciden.');  
                            }
                        }else{
                            $model->addError('password_anterior', 'La contraseña actual es incorrecta.');
                        }
                }
                $this->render('changePassword', array('model' => $model));
            }else{
                throw new CHttpException(403, Yii::t('app', 'You are not authorized to perform this action.'));
            }

	}
}

backend/views/alumno/_busqueda.php
<div class="wide form">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'search-alumno-form',
	'action'=>Yii::app()->createUrl($this->route),
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
	'method'=>'get',
        'htmlOptions'=>array('class'=>'well'),
)); ?>

	<?php echo $form->textFieldControlGroup($model,'id', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->textFieldControlGroup($model,'nombre', array('span'=>3, 'maxlength'=>255)); ?>

	<?php echo $form->textFieldControlGroup($model,'run', array('span'=>3, 'maxlength'=>12)); ?>

	<?php echo $form->textFieldControlGroup($model,'direccion', array('span'=>3, 'maxlength'=>45)); ?>

	<?php echo $form->dropDownListControlGroup($model,'user_id', GxHtml::listDataEx(User::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'All') ));?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton(Yii::t('app', 'Search'),  array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'icon'=>'white search'));?>
        <?php echo TbHtml::resetButton(Yii::t('app', 'Reset'), array('icon'=>'icon-remove-sign')); ?>
        </div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>


backend/views/alumno/_formulario.php

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'alumno-form',
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
        'enableAjaxValidation' => true,
));
?>

	<p class="help-block">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<?php echo $form->textFieldControlGroup($model,'nombre', array('span'=>3, 'maxlength'=>255)); ?>
		<?php echo $form->textFieldControlGroup($model,'run', array('span'=>3, 'maxlength'=>12)); ?>
		<?php echo $form->textFieldControlGroup($model,'direccion', array('span'=>3, 'maxlength'=>45)); ?>
		<?php echo $form->dropDownListControlGroup($model,'user_id', GxHtml::listDataEx(User::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>

<?php echo TbHtml::formActions(array(
    TbHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'id'=>'buttonStateful', 'data-loading-text'=>  Yii::t('app', 'Loading...'))),
    TbHtml::resetButton(Yii::t('app', 'Reset')),
));
?>
<?php $this->endWidget(); ?>        
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonStateful.js', CClientScript::POS_END); ?>

backend/views/alumno/ver.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('listar'),
	GxHtml::valueEx($model),
);

$this->menu=array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('actualizar', 'id' => $model->id), 'icon'=>'pencil'),
        array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('borrar', 'id' => $model->id), 'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?')), 'icon'=>'trash'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), null); ?>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
		'id',
		'nombre',
		'run',
		'direccion',
		array(
			'name' => 'user',
			'type' => 'raw',
			'value' => $model->user !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->user)), array('user/ver', 'id' => GxActiveRecord::extractPkValue($model->user, true))) : null,
			),
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('calificacions')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->calificacions as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('calificacion/ver', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('cursos')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->cursos as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('curso/ver', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('evaluacionSemestrals')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->evaluacionSemestrals as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('evaluacionSemestral/ver', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>

backend/views/alumno/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('list'),
	GxHtml::valueEx($model),
);

$this->menu=array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('list'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create'), 'url'=>array('create'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id), 'icon'=>'pencil'),
        array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?')), 'icon'=>'trash'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), TbHtml::labelTb('Admin')); ?>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
		'id',
		'nombre',
		'run',
		'direccion',
		array(
			'name' => 'user',
			'type' => 'raw',
			'value' => $model->user !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->user)), array('user/view', 'id' => GxActiveRecord::extractPkValue($model->user, true))) : null,
			),
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('calificacions')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->calificacions as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('calificacion/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('cursos')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->cursos as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('curso/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('evaluacionSemestrals')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->evaluacionSemestrals as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('evaluacionSemestral/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>